# Generated by Django 2.2.3 on 2019-07-22 20:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_auto_20190721_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='home',
            field=models.ManyToManyField(blank=True, related_name='home_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='vacant',
            field=models.ManyToManyField(blank=True, related_name='vacant_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='free_places',
            field=models.IntegerField(blank=True, default=14, validators=[django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DutyAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
